#!/bin/sh
cordova create uploadPhoto com.yzhou.uploadPhoto uploadPhoto
cd uploadPhoto
cordova platform add android
cordova platform add ios
cordova plugin add org.apache.cordova.file-transfer
cordova plugin add org.apache.cordova.camera
cordova plugin add org.apache.cordova.file
cordova plugin add org.apache.cordova.network-information
cordova plugin add org.apache.cordova.inappbrowser
cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.device-motion
